// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLQuy2etrhlb2brXK2HKKWF-0WQvp29hU',
    appId: '1:614022234463:web:26bdf938543e59ba01b6ea',
    messagingSenderId: '614022234463',
    projectId: 'rental-management-app-d17eb',
    authDomain: 'rental-management-app-d17eb.firebaseapp.com',
    databaseURL: 'https://rental-management-app-d17eb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rental-management-app-d17eb.firebasestorage.app',
    measurementId: 'G-SKS7YWWTTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE9UHggKqMfPz7KxEzHlYgdA0WN8WTwr0',
    appId: '1:614022234463:android:c49e0ac746d5f25201b6ea',
    messagingSenderId: '614022234463',
    projectId: 'rental-management-app-d17eb',
    databaseURL: 'https://rental-management-app-d17eb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rental-management-app-d17eb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLQuy2etrhlb2brXK2HKKWF-0WQvp29hU',
    appId: '1:614022234463:web:cd0e9964a778fdd901b6ea',
    messagingSenderId: '614022234463',
    projectId: 'rental-management-app-d17eb',
    authDomain: 'rental-management-app-d17eb.firebaseapp.com',
    databaseURL: 'https://rental-management-app-d17eb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rental-management-app-d17eb.firebasestorage.app',
    measurementId: 'G-9F0QHVZ9CR',
  );

}